# Установка пути для плагинов
# test
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins/'

# Использовать Zsh как оболочку по умолчанию
# set -g default-shell /bin/fish

# Начинать нумерацию окон и панелей с 1
set -g base-index 1
set -g renumber-windows on

# Перезагрузка конфига по клавише 'r'
unbind r
bind r source-file ~/.tmux.conf

# Настройка терминала
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Включить поддержку мыши
set -g mouse on

# Использовать режим vi для навигации
set-window-option -g mode-keys vi
# Enable vi mode to allow us to use vim keys to move around in copy mode (Prefix + [ places us in copy mode)
set-window-option -g mode-keys vi

# Start selecting text with "v"
bind-key -T copy-mode-vi 'v' send -X begin-selection 

# Copy text with "y"
bind -T copy-mode-vi 'y' send-keys -X copy-pipe-and-cancel "wl-copy"

# Paste yanked text with "Prefix + P" ("Prefix + p" goes to previous window)
bind P paste-buffer
 
# Don't exit copy mode when dragging with mouse
unbind -T copy-mode-vi MouseDragEnd1Pane
# Привязки клавиш для переключения панелей
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# Настройка Ctrl-Y как клавиши подтверждения в tmux
# В режиме выбора (например, при выборе pane с помощью C-b s)
bind-key -T copy-mode-vi C-y send-keys -X confirm-before

# Set new panes to open in current directory
bind c new-window -c "#{pane_current_path}"
bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"

# Позиция статусной строки
set-option -g status-position top
set -g set-clipboard on         # Use system clipboard
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# Список плагинов
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'christoomey/vim-tmux-navigator'
# set -g @plugin 'catppuccin/tmux#v2.1.3'
# set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'laktak/extrakto'
# set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes
# set -g @plugin 'hendrikmi/tmux-cpu-mem-monitor' # CPU and memory info
set -g @extrakto_key "e"
# Настройка статусной строки
# set -g @catppuccin_flavor "mocha"

bg="#1c1c1c"
# bg="#313244"                      # Base
default_fg="#CDD6F4"             # Text
session_fg="#A6E3A1"             # Green
session_selection_fg="#1E1E2E"  # Base (на фоне выделения)
session_selection_bg="#89B4FA"  # Blue
active_window_fg="#89DCEB"      # Sky
active_pane_border="#BAC2DE"    # Surface2


set -g status-left-length 200   # default: 10
set -g status-right-length 200  # default: 10
set -g status-left "#[fg=${session_fg},bold,bg=${bg}]  #S"
# set -g status-right "#{pane_current_path}"
set -g status-right "        "
set -g status-justify centre
set -g status-style "bg=${bg}"
set -g window-status-format "#[fg=${default_fg},bg=default] #I:#W"
set -g window-status-current-format "#[fg=${active_window_fg},bg=default]  #I:#W"
set -g window-status-last-style "fg=${default_fg},bg=default"
set -g message-command-style "bg=default,fg=${default_fg}"
set -g message-style "bg=default,fg=${default_fg}"
set -g mode-style "bg=${session_selection_bg},fg=${session_selection_fg}"
set -g pane-active-border-style "fg=${active_pane_border},bg=default"
set -g pane-border-style "fg=brightblack,bg=default"


# Popup сессия, уникальная для директории
bind g run-shell 'tmux display-popup -d "#{pane_current_path}" -xC -yC -w 80% -h 75% -E "tmux new-session -A -s popup_$(basename #{pane_current_path} | tr -cd a-zA-Z0-9-)"'

# Глобальный popup (одна общая сессия)
bind G run-shell 'tmux display-popup -xC -yC -w 80% -h 75% -E "tmux new-session -A -s popup_global"'

# Инициализация TPM (должна быть в конце файла)
run '~/.tmux/plugins/tpm/tpm'
